"""Migración con modelos ya escritos

Revision ID: b32e676cf80c
Revises: 
Create Date: 2025-04-01 12:59:27.831663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32e676cf80c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niveles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('solicitud_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curp', sa.String(length=18), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('paterno', sa.String(length=100), nullable=True),
    sa.Column('materno', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('id_nivel', sa.Integer(), nullable=True),
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.Column('id_asunto', sa.Integer(), nullable=True),
    sa.Column('turno', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('Pendiente', 'Resuelto'), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_asunto'], ['asuntos.id'], ),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['id_nivel'], ['niveles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_turno')
    op.drop_table('usuario')
    op.drop_table('niveles')
    op.drop_table('municipios')
    op.drop_table('asuntos')
    # ### end Alembic commands ###
