"""Agregar campo nombre_tramite

Revision ID: b4a0b07887ed
Revises: b32e676cf80c
Create Date: 2025-04-02 12:25:23.721654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4a0b07887ed'
down_revision = 'b32e676cf80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_turno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_tramite', sa.String(length=100), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('solicitud_turno', schema=None) as batch_op:
        batch_op.drop_column('nombre_tramite')

    # ### end Alembic commands ###
